#!/bin/bash
SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )" # thanks https://stackoverflow.com/a/4774063/920295
if [[ $SCRIPTPATH == *"AppTranslocation"* ]]; then
  osascript -e "display alert \"Please copy this application somewhere on your machine. It can't be run from the image.\" as critical"
else
  open -a Terminal "$SCRIPTPATH/OnChromeExecutable"
fi
